<a href="https://colab.research.google.com/github/RafaelCaballero/Julio25/blob/main/proyectoRegresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a la ciencia de datos con Python
Rafa Caballero

## Proyecto: regresión logística

Comenzamos cargando algunos datos

In [11]:
import pandas as pd
import yfinance as yf
import numpy as np

valores = ["AAPL","AMZN","GOOG","NFLX","MSFT","SHEL","LLY"]
for v in valores:
    #print(v)
    df = yf.download(v,
                    start='2021-01-01',
                     end='2026-06-30',
                     multi_level_index=False)

    # además lo renombramos
    df.columns = [c+"_"+v for c in df.columns]
    if v==valores[0]:
        df_total = df
    else:
        df_total = pd.concat([df_total, df], axis=1)

df_total = df_total.pct_change().dropna()

/tmp/ipykernel_3203/3705200975.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/3705200975.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/3705200975.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/3705200975.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/3705200975.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/3705200975.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/3705200975.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,
[*********************100%***********************]  1 of 1 completed

Marcamos con 1 las columnas en las que AAPL-Close supera la media de la serie histórica

In [5]:
filtro = df_total["Close_AAPL"]> df_total["Close_AAPL"].mean()
df_total.loc[filtro,"label"]=1
df_total.loc[~filtro,"label"]=0
# la ponemos la primera para que se vea mejor
first_column = df_total.pop('label')
df_total.insert(0, 'label', first_column)
df_total

,label,Close_AAPL,High_AAPL,Low_AAPL,Open_AAPL,Volume_AAPL,Close_AMZN,High_AMZN,Low_AMZN,Open_AMZN,...,Close_SHEL,High_SHEL,Low_SHEL,Open_SHEL,Volume_SHEL,Close_LLY,High_LLY,Low_LLY,Open_LLY,Volume_LLY
Date,,,,,,,,,,,,,,,,,,,,,
2008-01-03,0.0,0.000462,-0.014331,0.000727,-0.019371,-0.219716,-0.010805,-0.001847,-0.001901,0.007446,...,0.021410,0.012002,0.004600,0.014646,-0.273871,0.008373,-0.011529,0.007852,-0.013843,-0.187770
2008-01-04,0.0,-0.076334,-0.022240,-0.071617,-0.020264,0.728880,-0.067430,-0.039589,-0.063690,-0.029148,...,-0.020263,0.003721,0.000238,0.004889,0.106863,-0.022457,-0.006207,-0.017864,-0.003414,0.370696
2008-01-07,0.0,-0.013385,-0.048705,-0.048410,-0.053278,0.423374,0.000338,-0.030300,-0.034237,-0.049753,...,0.024605,0.001042,0.015340,0.000116,1.020228,0.053089,0.035964,0.009481,-0.006281,0.677217
2008-01-08,0.0,-0.035972,-0.006210,0.003348,-0.006125,-0.264636,-0.010583,0.013912,0.017082,-0.012074,...,-0.035962,-0.013539,-0.028343,-0.012973,-0.260416,0.027681,0.045496,0.042936,0.049990,0.175577
2008-01-09,1.0,0.047592,-0.016222,-0.014637,-0.049073,0.190355,-0.030269,-0.043885,-0.076958,0.000114,...,0.013839,-0.007274,0.003978,-0.020655,-0.063244,0.014271,-0.001573,0.030142,0.022437,-0.214832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-23,0.0,-0.009124,-0.002579,-0.008694,0.000774,0.158891,0.005670,-0.021198,-0.001033,-0.031365,...,-0.001883,-0.004751,0.000380,-0.002517,-0.036083,0.004537,0.002296,-0.012743,0.004280,0.099934
2026-06-24,0.0,-0.004145,-0.006432,-0.004215,-0.007327,0.020592,0.000683,0.023431,0.004095,0.005590,...,-0.022764,-0.016330,-0.022298,-0.017539,0.834640,0.009195,0.011693,0.020163,0.011110,-0.123059
2026-06-25,0.0,-0.061178,-0.036370,-0.065508,-0.026950,1.016011,-0.030990,-0.041663,-0.031766,-0.007826,...,-0.004762,-0.010216,-0.004795,-0.009761,-0.347410,0.009335,0.009065,0.011826,-0.002143,-0.051922
2026-06-26,1.0,0.031365,-0.009868,0.001680,-0.043145,1.446187,0.025021,0.006801,0.002571,-0.020731,...,-0.010345,-0.005548,-0.005404,-0.000648,-0.261807,0.071323,0.061400,0.012567,0.001606,1.802046
2026-06-29,0.0,-0.007189,0.008463,0.020568,0.042655,-0.746244,0.032017,0.067593,0.033919,0.030852,...,0.004704,0.002205,0.004058,-0.000454,0.722940,0.018053,0.018293,0.066613,0.083257,-0.523066

**Ejercicio**

Intentar enteder las siguientes instrucciones ¿qué efecto tienen? (pista: fijarse en la columna "label")

In [6]:
df = df_total.copy()

f = 2 # futuro
df.iloc[0:-f,0] = df.iloc[f:,0]
df = df.iloc[0:-f]
df

,label,Close_AAPL,High_AAPL,Low_AAPL,Open_AAPL,Volume_AAPL,Close_AMZN,High_AMZN,Low_AMZN,Open_AMZN,...,Close_SHEL,High_SHEL,Low_SHEL,Open_SHEL,Volume_SHEL,Close_LLY,High_LLY,Low_LLY,Open_LLY,Volume_LLY
Date,,,,,,,,,,,,,,,,,,,,,
2008-01-03,0.0,0.000462,-0.014331,0.000727,-0.019371,-0.219716,-0.010805,-0.001847,-0.001901,0.007446,...,0.021410,0.012002,0.004600,0.014646,-0.273871,0.008373,-0.011529,0.007852,-0.013843,-0.187770
2008-01-04,0.0,-0.076334,-0.022240,-0.071617,-0.020264,0.728880,-0.067430,-0.039589,-0.063690,-0.029148,...,-0.020263,0.003721,0.000238,0.004889,0.106863,-0.022457,-0.006207,-0.017864,-0.003414,0.370696
2008-01-07,0.0,-0.013385,-0.048705,-0.048410,-0.053278,0.423374,0.000338,-0.030300,-0.034237,-0.049753,...,0.024605,0.001042,0.015340,0.000116,1.020228,0.053089,0.035964,0.009481,-0.006281,0.677217
2008-01-08,1.0,-0.035972,-0.006210,0.003348,-0.006125,-0.264636,-0.010583,0.013912,0.017082,-0.012074,...,-0.035962,-0.013539,-0.028343,-0.012973,-0.260416,0.027681,0.045496,0.042936,0.049990,0.175577
2008-01-09,0.0,0.047592,-0.016222,-0.014637,-0.049073,0.190355,-0.030269,-0.043885,-0.076958,0.000114,...,0.013839,-0.007274,0.003978,-0.020655,-0.063244,0.014271,-0.001573,0.030142,0.022437,-0.214832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-22,0.0,-0.003356,0.006155,0.003856,-0.002684,-0.477911,-0.047465,-0.015179,-0.016016,-0.000167,...,0.010786,0.013045,0.012382,0.012876,-0.339643,0.003195,-0.002566,0.004124,-0.007363,-0.325579
2026-06-23,0.0,-0.009124,-0.002579,-0.008694,0.000774,0.158891,0.005670,-0.021198,-0.001033,-0.031365,...,-0.001883,-0.004751,0.000380,-0.002517,-0.036083,0.004537,0.002296,-0.012743,0.004280,0.099934
2026-06-24,0.0,-0.004145,-0.006432,-0.004215,-0.007327,0.020592,0.000683,0.023431,0.004095,0.005590,...,-0.022764,-0.016330,-0.022298,-0.017539,0.834640,0.009195,0.011693,0.020163,0.011110,-0.123059
2026-06-25,1.0,-0.061178,-0.036370,-0.065508,-0.026950,1.016011,-0.030990,-0.041663,-0.031766,-0.007826,...,-0.004762,-0.010216,-0.004795,-0.009761,-0.347410,0.009335,0.009065,0.011826,-0.002143,-0.051922
2026-06-26,0.0,0.031365,-0.009868,0.001680,-0.043145,1.446187,0.025021,0.006801,0.002571,-0.020731,...,-0.010345,-0.005548,-0.005404,-0.000648,-0.261807,0.071323,0.061400,0.012567,0.001606,1.802046

**Ejercicio**
Eliminar de df todas las columnas relacionadas con AAPL, porque lo que buscamos es ver si Apple va a tener un incremento a partir del resto. Se puede escribir el nombre de las columnas a borrar a mano

In [ ]:
print(df.columns)
# Solución

**Ejercicio**

Utilizar regresión logística para intentar determinar label a partir del resto de columnas en df. Se puede utilizar la siguiente función para mostrar los resultados:

In [7]:
from sklearn.metrics import classification_report
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
def evaluar(y_test,y_pred):
  k =  cohen_kappa_score(y_test,y_pred)
  print("kappa ",k)
  cm = confusion_matrix(y_test, y_pred, labels=modelo.classes_)
  disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                                display_labels=modelo.classes_)
  disp.plot()

  plt.show()

  print(classification_report(y_test, y_pred))
  return k,cm

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import RocCurveDisplay
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
from sklearn.metrics import make_scorer,f1_score, accuracy_score, recall_score,cohen_kappa_score

from sklearn.linear_model import LogisticRegression

### Solución

¿Cuál es el peor valor entre precision y recall que se obtiene? ¿qué indica? ¿a qué puede deberse?

**Ejercicio**

PArtimos de los mismos datos:

In [10]:
import pandas as pd
import yfinance as yf
import numpy as np

valores = ["AAPL","AMZN","GOOG","NFLX","MSFT","SHEL","LLY"]
for v in valores:
    #print(v)
    df = yf.download(v,   multi_level_index=False,
                          start='2021-01-01',
                          end='2026-06-30')

    # además lo renombramos
    df.columns = [c+"_"+v for c in df.columns]
    if v==valores[0]:
        df_total = df
    else:
        df_total = pd.concat([df_total, df], axis=1)

df_total = df_total.pct_change().dropna()
df_total

/tmp/ipykernel_3203/2872946795.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,   multi_level_index=False,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/2872946795.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,   multi_level_index=False,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/2872946795.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,   multi_level_index=False,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/2872946795.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,   multi_level_index=False,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/2872946795.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,   multi_level_index=False,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/2872946795.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,   multi_level_index=False,
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3203/2872946795.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(v,   multi_level_index=False,
[*********************100%***********************]  1 of 1 completed

,Close_AAPL,High_AAPL,Low_AAPL,Open_AAPL,Volume_AAPL,Close_AMZN,High_AMZN,Low_AMZN,Open_AMZN,Volume_AMZN,...,Close_SHEL,High_SHEL,Low_SHEL,Open_SHEL,Volume_SHEL,Close_LLY,High_LLY,Low_LLY,Open_LLY,Volume_LLY
Date,,,,,,,,,,,,,,,,,,,,,
2008-01-03,0.000462,-0.014332,0.000727,-0.019371,-0.219716,-0.010805,-0.001847,-0.001901,0.007446,-0.341749,...,0.021411,0.012003,0.004601,0.014647,-0.273871,0.008373,-0.011529,0.007852,-0.013843,-0.187770
2008-01-04,-0.076335,-0.022240,-0.071618,-0.020265,0.728880,-0.067430,-0.039589,-0.063690,-0.029148,0.125788,...,-0.020263,0.003721,0.000238,0.004889,0.106863,-0.022457,-0.006207,-0.017864,-0.003414,0.370696
2008-01-07,-0.013385,-0.048705,-0.048410,-0.053278,0.423374,0.000338,-0.030300,-0.034237,-0.049753,-0.028082,...,0.024605,0.001042,0.015340,0.000116,1.020228,0.053089,0.035965,0.009482,-0.006281,0.677217
2008-01-08,-0.035972,-0.006209,0.003348,-0.006124,-0.264636,-0.010583,0.013912,0.017082,-0.012074,0.230594,...,-0.035963,-0.013540,-0.028344,-0.012973,-0.260416,0.027681,0.045496,0.042937,0.049991,0.175577
2008-01-09,0.047591,-0.016223,-0.014637,-0.049073,0.190355,-0.030269,-0.043885,-0.076958,0.000114,0.336033,...,0.013839,-0.007274,0.003978,-0.020655,-0.063244,0.014270,-0.001573,0.030141,0.022437,-0.214832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-06-24,0.003133,0.003823,-0.002511,-0.012691,-0.666148,-0.018564,0.009087,-0.002852,0.008147,-0.285088,...,0.021161,0.017987,0.010890,0.007845,0.107094,0.007048,0.013016,0.003569,0.004878,-0.164747
2024-06-25,0.004468,-0.006206,0.009778,0.006884,-0.311882,0.004149,-0.011309,0.000486,-0.013310,-0.103615,...,0.001820,0.001047,0.009497,0.013020,-0.300168,0.016290,0.006463,0.009695,0.002011,-0.016712
2024-06-26,0.019993,0.016463,0.009731,0.011236,0.191963,0.039015,0.031561,0.004530,0.000589,0.435069,...,-0.009643,-0.009069,-0.010390,-0.009919,0.891806,-0.003703,-0.003376,0.007112,0.013714,-0.211300
2024-06-27,0.003986,0.004096,0.008118,0.015083,-0.248296,0.021900,0.025873,0.042629,0.043281,0.142750,...,0.008185,0.010842,0.009506,0.011288,-0.246811,0.008632,0.003553,0.002094,-0.000520,-0.127234
2024-06-28,-0.016254,0.001530,-0.009654,0.005030,0.658393,-0.023250,-0.004954,-0.008754,0.013948,0.034043,...,0.010358,0.007089,0.007027,0.004326,0.432639,-0.004026,0.006564,0.006291,0.008611,0.732663

Ahora queremos obtener el incremento de Close_AAPL mediante regresión

En particular se propone:

1) Eliminar todas las columnas relacionadas con APPL excepto CLOSE_APPL

2) Usar regresión lineal para intentar calcularla

Se propone usar los 4 pasos (sin validación cruzada)

In [ ]:
#  Solución

**Ejercicio**

Examinar los coeficientes del modelo ¿Qué indican?

**Ejercicio**

Hacerlo ahora con validación cruzada

**Ejercicio**

Probar algún otro método de regresión como RandomForestRegressor o GradientBoostingRegressor ¿se mejora el error?